# -*- coding: utf-8 -*-
"""Morpion01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10DyzR0fpmhYDeOp-HZGa5iOH0BYVHgPP
"""

from IPython.display import display, HTML, clear_output

def afficher_plateau(p, gagnant=None):
    clear_output(wait=True)
    html = f"""
    <div style="font-size:20px; line-height:1.5; text-align:center; margin-bottom: 10px;">
        <span style="color: #1f618d;">{p[0]}</span> | <span style="color: #1f618d;">{p[1]}</span> | <span style="color: #1f618d;">{p[2]}</span><br>
        ---------<br>
        <span style="color: #1f618d;">{p[3]}</span> | <span style="color: #1f618d;">{p[4]}</span> | <span style="color: #1f618d;">{p[5]}</span><br>
        ---------<br>
        <span style="color: #1f618d;">{p[6]}</span> | <span style="color: #1f618d;">{p[7]}</span> | <span style="color: #1f618d;">{p[8]}</span>
    </div>
    """
    if gagnant:
        html += f"<p style='color: #1f618d; font-size: 18px;'>* Partie terminée : le joueur {gagnant} a gagné. *</p>"
    display(HTML(html))

def morpion():
    plateau = [" " for _ in range(9)]
    joueurs = ["X", "O"]
    tour = 0

    while True:
        joueur = joueurs[tour % 2]

        afficher_plateau(plateau)

        try:
            move = int(input(f"Tour du joueur {joueur}. Entrez un nombre de 1 à 9: ")) - 1
            if not (0 <= move < 9) or plateau[move] != " ":
                raise ValueError("Veuillez choisir une case valide.")
        except ValueError as e:
            print(f"Erreur : {e}")
            continue

        plateau[move] = joueur

        if any(all(plateau[i] == joueur for i in line) for line in [(0, 1, 2), (3, 4, 5), (6, 7, 8),
                                                                     (0, 3, 6), (1, 4, 7), (2, 5, 8),
                                                                     (0, 4, 8), (2, 4, 6)]):
            afficher_plateau(plateau, joueur)
            print(f"Félicitations ! Le joueur {joueur} a gagné.")
            break

        tour += 1

        if tour == 9:
            afficher_plateau(plateau)
            print("Égalité ! La partie est terminée.")
            break

if __name__ == "__main__":
    morpion()

